feat: Create Event
mash-up-kr/gabbangzip-spring pull request #44
Opened 2024-07-28 09:17 UTC by 210-reverof

## 🛠 Changes
- 화면 플로우에 맞게 req/res 값 변경
- group join / event join 관련 속성 수정

## 🧚‍♀️ To Reviewers
- 레이어 관련 의견들이 맞게 적용된거일까용

## 🎒 Related Issues (optional)

## 👔 Check List
- [X] PR 이름이 맞게 작성되었는가? (ex. feat: User login ~)
- [X] Test가 성공적으로 실행되는가?

2024-07-28 09:29 UTC, bbeomgeun commented on pic-api/src/main/kotlin/com/mashup/pic/event/controller/EventController.kt
> +        println("=============")
ㅋㅋㅋㅋㅋ 이거 머에여

2024-07-28 09:30 UTC, bbeomgeun commented on pic-api/src/main/kotlin/com/mashup/pic/event/controller/dto/CreateEventRequest.kt
> +    @field:Size(min = 4, max = 4) val pictures: List<String>
질문)
이거 무조건 4장 넣는거 정책인거죠??

2024-07-28 09:31 UTC, 210-reverof commented on pic-api/src/main/kotlin/com/mashup/pic/event/controller/EventController.kt
> +        println("=============")
앗 이런 부끄러운 ㅎ~ 계속 url이 안 먹길래 진짜 답답해서,, 오타 이슈엿슴당

2024-07-28 09:32 UTC, bbeomgeun commented on pic-domain/src/main/kotlin/com/mashup/pic/domain/event/EventService.kt
> +        println("=============================" + groupId)
요기도~

2024-07-28 09:33 UTC, 210-reverof commented on pic-domain/src/main/kotlin/com/mashup/pic/domain/event/EventService.kt
> +        println("=============================" + groupId)
헤헤 감사요ㅛ

2024-07-28 09:33 UTC, 210-reverof commented on pic-api/src/main/kotlin/com/mashup/pic/event/controller/dto/CreateEventRequest.kt
> +    @field:Size(min = 4, max = 4) val pictures: List<String>
넹 맞아용

2024-07-28 17:48 UTC, mkSpace requested changes

2024-07-28 17:48 UTC, mkSpace commented on pic-api/src/main/kotlin/com/mashup/pic/event/controller/dto/CreateEventRequest.kt
> +    @field:NotBlank val description: String,
맞지 않을때의 errorMessage도 같이 작성해주심 좋겠네요

2024-07-28 17:48 UTC, mkSpace commented on pic-domain/src/main/kotlin/com/mashup/pic/domain/event/EventService.kt
> +                message = "$groupId 에 해당하는 그룹를 찾을 수 없습니다."
```suggestion
                message = "$groupId 에 해당하는 그룹을 찾을 수 없습니다."
```

2024-07-28 17:48 UTC, mkSpace commented on pic-domain/src/main/kotlin/com/mashup/pic/domain/event/EventService.kt
> +    ): Long {
id만 반환하는 이유가 있나요?

2024-07-28 17:48 UTC, mkSpace commented on pic-domain/src/main/kotlin/com/mashup/pic/domain/event/EventService.kt
> +    private val eventJoinRepository: EventJoinRepository
따로 나누지 않으셨네요?

2024-07-29 00:52 UTC, 210-reverof commented on pic-domain/src/main/kotlin/com/mashup/pic/domain/event/EventService.kt
> +    ): Long {
플로우상 id로 상세보기 api 호출 예정이기 때문입니당

2024-07-29 00:54 UTC, 210-reverof commented on pic-domain/src/main/kotlin/com/mashup/pic/domain/event/EventService.kt
> +    private val eventJoinRepository: EventJoinRepository
엇 구체적으로 어떻게 나누는 걸 말씀하시는지 제가 이해못한 것 같아요

2024-07-29 14:53 UTC, bbeomgeun approved these changes

2024-07-29 15:35 UTC, merged