feat: Join with invitation code
mash-up-kr/gabbangzip-spring pull request #45
Opened 2024-07-28 13:05 UTC by 210-reverof

## 🛠 Changes
- 초대코드로 그룹에 참여할 수 있도록 한다.

## 🧚‍♀️ To Reviewers
- 이전 PR에서 추가된 Group Entity 속성을 이용하는 부분이 아직 추가되지 않았습니다. (인원 수 제한)
- repository에서 Entity 가져오는 부분들은 계속 재사용될 것 같아 따로 메서드로 뽑았습니당

## 🎒 Related Issues (optional)

## 👔 Check List
- [X] PR 이름이 맞게 작성되었는가? (ex. feat: User login ~)
- [X] Test가 성공적으로 실행되는가?

2024-07-28 17:51 UTC, mkSpace requested changes

2024-07-28 17:51 UTC, mkSpace commented on pic-api/src/main/kotlin/com/mashup/pic/util/InviteCodeUtil.kt
> +object InviteCodeUtil {
```suggestion
object InvitationCodeUtil {
```

2024-07-28 17:51 UTC, mkSpace commented on pic-domain/src/main/kotlin/com/mashup/pic/domain/group/GroupService.kt
> +        // TODO: 4명 이상일 때 예외던지기: Group의 joins 수 가져오기
4명 이상일 때 실패 <-- 이건 비즈니스 로직아닌가요? 이건 ApplicationService에 있어야 할 것 같네요

2024-07-28 17:51 UTC, mkSpace commented on pic-domain/src/main/kotlin/com/mashup/pic/domain/group/GroupService.kt
> +            throw PicException.of(PicExceptionType.ARGUMENT_NOT_VALID, "이미 참여")
```suggestion
            throw PicException.of(PicExceptionType.ARGUMENT_NOT_VALID, "이미 참여한 유저입니다.")
```

2024-07-29 14:20 UTC, bbeomgeun approved these changes

2024-07-29 15:41 UTC, merged